name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - xarray
    - intake
    - intake-xarray==0.3.1
    - intake-geopandas
    - aiohttp
    - fsspec
    - cookiecutter
    - dask
    - distributed
    - h5py
    - netcdf4
    - tqdm
    - pandas
    - scipy
    - matplotlib
    - owslib
    - pytest
    - geopandas
