name: Test PyPI Publishing

on:
  push:

jobs:
  test-deploy:
    name: Test PyPI Publishing Process
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
        pip install .[dev]
    -
      name: Run tests
      run: pytest -s -v tests
    -
      name: Run linting
      run: |
        pip install ruff
        ruff check .
    -
      name: Build package
      run: python -m build
    -
      name: Check built package
      run: |
        pip install twine
        twine check dist/*
